name: C CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [ dev, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run : sudo apt update && sudo apt install libsdl2-dev libsdl2-image-dev
    - name: make
      run: make ocr
